
import courseIcon1 from '../../assets/courseIcon1.png';
import courseIcon2 from '../../assets/courseIcon2.png';
import courseIcon3 from '../../assets/courseIcon3.png';
import courseIcon4 from '../../assets/courseIcon4.png';
import courseIcon5 from '../../assets/courseIcon5.png';
import courseIcon6 from '../../assets/courseIcon6.png';


export const courseInfo = [
    [
            {
                id: 1,
                title: 'اللوائح المالية',
                text: 'تغطى الدورة التدريبية كافة اللوائح الداخلية المالية المعمول بها داخل البنك وكيفية أتباعها بطريقة صحيحة',
                firstText: '٤ أيام',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات الوظيفية',
                thirdIcon: courseIcon4,
            },
            {
                id: 2,
                title: 'المراقبة والمراجعة',
                text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية الرقابة الداخلية والمراجعة وكيفية متابعتها',
                firstText: 'يومين',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات القيادية',
                thirdIcon: courseIcon5,
            },
            {
                id: 3,
                title: 'إدارة المخاطر',
                text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية إدارة المخاطر وكيفية وضع خطة إدارة المخاطر',
                firstText: '٤ أيام',
                firstIcon: courseIcon1,
                secondText: 'مركز تدريب البنك الأهلي',
                secondIcon: courseIcon3,
                thirdText: 'الكفاءات الاساسية',
                thirdIcon: courseIcon6,
            },
            {
                id: 4,
                title: 'غسل الأموال',
                text: 'تغطي الدورة التدريبية الأساليب المختلفة لعملية غسل الأموال وكيفية مكافحتها بالطريقة الصحيحة',
                firstText: '٣ أيام',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات الوظيفية',
                thirdIcon: courseIcon4,
            },
            {
                id: 5,
                title: 'اللوائح ',
                text: 'تغطى الدورة التدريبية كافة اللوائح الداخلية المالية المعمول بها داخل البنك وكيفية أتباعها بطريقة صحيحة',
                firstText: '٤ أيام',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات الوظيفية',
                thirdIcon: courseIcon4,
            },
            {
                id: 6,
                title: 'المراقبة ',
                text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية الرقابة الداخلية والمراجعة وكيفية متابعتها',
                firstText: 'يومين',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات القيادية',
                thirdIcon: courseIcon5,
            },
            {
                id: 7,
                title: 'إدارة الشرطة',
                text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية إدارة المخاطر وكيفية وضع خطة إدارة المخاطر',
                firstText: '٤ أيام',
                firstIcon: courseIcon1,
                secondText: 'مركز تدريب البنك الأهلي',
                secondIcon: courseIcon3,
                thirdText: 'الكفاءات الاساسية',
                thirdIcon: courseIcon6,
            },
            {
                id: 8,
                title: 'غسل ا الملابس',
                text: 'تغطي الدورة التدريبية الأساليب المختلفة لعملية غسل الأموال وكيفية مكافحتها بالطريقة الصحيحة',
                firstText: '٣ أيام',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات الوظيفية',
                thirdIcon: courseIcon4,
            }
        ],
        [
            {
                id: 1,
                title: 'التكنولوجيا',
                text: 'تغطى الدورة التدريبية كافة اللوائح الداخلية المالية المعمول بها داخل البنك وكيفية أتباعها بطريقة صحيحة',
                firstText: '٤ أيام',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات الوظيفية',
                thirdIcon: courseIcon3,
            },
            {
                id: 2,
                title: 'المراقبة والمراجعة2',
                text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية الرقابة الداخلية والمراجعة وكيفية متابعتها',
                firstText: 'يومين',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات القيادية',
                thirdIcon: courseIcon4,
            },
            {
                id: 3,
                title: 'إدارة المخاطر3',
                text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية إدارة المخاطر وكيفية وضع خطة إدارة المخاطر',
                firstText: '٤ أيام',
                firstIcon: courseIcon1,
                secondText: 'مركز تدريب البنك الأهلي',
                secondIcon: courseIcon4,
                thirdText: 'الكفاءات الاساسية',
                thirdIcon: courseIcon5,
            },
            {
                id: 4,
                title: 'غسل الأموال4',
                text: 'تغطي الدورة التدريبية الأساليب المختلفة لعملية غسل الأموال وكيفية مكافحتها بالطريقة الصحيحة',
                firstText: '٣ أيام',
                firstIcon: courseIcon1,
                secondText: 'التدريب الإلكتروني',
                secondIcon: courseIcon2,
                thirdText: 'الكفاءات الوظيفية',
                thirdIcon: courseIcon6,
            }
    ],
    [
        {
            id: 1,
            title: 'التكنولوجيا3',
            text: 'تغطى الدورة التدريبية كافة اللوائح الداخلية المالية المعمول بها داخل البنك وكيفية أتباعها بطريقة صحيحة',
            firstText: '٤ أيام',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات الوظيفية',
            thirdIcon: courseIcon3,
        },
        {
            id: 2,
            title: 'المراقبة والمراجعة3',
            text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية الرقابة الداخلية والمراجعة وكيفية متابعتها',
            firstText: 'يومين',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات القيادية',
            thirdIcon: courseIcon4,
        },
        {
            id: 3,
            title: 'إدارة المخاطر4',
            text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية إدارة المخاطر وكيفية وضع خطة إدارة المخاطر',
            firstText: '٤ أيام',
            firstIcon: courseIcon1,
            secondText: 'مركز تدريب البنك الأهلي',
            secondIcon: courseIcon4,
            thirdText: 'الكفاءات الاساسية',
            thirdIcon: courseIcon5,
        },
        {
            id: 4,
            title: 'غسل الأموال4',
            text: 'تغطي الدورة التدريبية الأساليب المختلفة لعملية غسل الأموال وكيفية مكافحتها بالطريقة الصحيحة',
            firstText: '٣ أيام',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات الوظيفية',
            thirdIcon: courseIcon6,
        }
    ],
    [
        {
            id: 1,
            title: 'التدريب',
            text: 'تغطى الدورة التدريبية كافة اللوائح الداخلية المالية المعمول بها داخل البنك وكيفية أتباعها بطريقة صحيحة',
            firstText: '٤ أيام',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات الوظيفية',
            thirdIcon: courseIcon3,
        },
        {
            id: 2,
            title: 'المراقبة والمراجعة2',
            text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية الرقابة الداخلية والمراجعة وكيفية متابعتها',
            firstText: 'يومين',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات القيادية',
            thirdIcon: courseIcon4,
        },
        {
            id: 3,
            title: 'إدارة المخاطر3',
            text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية إدارة المخاطر وكيفية وضع خطة إدارة المخاطر',
            firstText: '٤ أيام',
            firstIcon: courseIcon1,
            secondText: 'مركز تدريب البنك الأهلي',
            secondIcon: courseIcon4,
            thirdText: 'الكفاءات الاساسية',
            thirdIcon: courseIcon5,
        },
        {
            id: 4,
            title: 'غسل الأموال4',
            text: 'تغطي الدورة التدريبية الأساليب المختلفة لعملية غسل الأموال وكيفية مكافحتها بالطريقة الصحيحة',
            firstText: '٣ أيام',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات الوظيفية',
            thirdIcon: courseIcon6,
        }
    ],
    [
        {
            id: 1,
            title: 'الادارة الاستراتيجية',
            text: 'تغطى الدورة التدريبية كافة اللوائح الداخلية المالية المعمول بها داخل البنك وكيفية أتباعها بطريقة صحيحة',
            firstText: '٤ أيام',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات الوظيفية',
            thirdIcon: courseIcon3,
        },
        {
            id: 2,
            title: 'المراقبة والمراجعة2',
            text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية الرقابة الداخلية والمراجعة وكيفية متابعتها',
            firstText: 'يومين',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات القيادية',
            thirdIcon: courseIcon4,
        },
        {
            id: 3,
            title: 'إدارة المخاطر3',
            text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية إدارة المخاطر وكيفية وضع خطة إدارة المخاطر',
            firstText: '٤ أيام',
            firstIcon: courseIcon1,
            secondText: 'مركز تدريب البنك الأهلي',
            secondIcon: courseIcon4,
            thirdText: 'الكفاءات الاساسية',
            thirdIcon: courseIcon5,
        },
        {
            id: 4,
            title: 'غسل الأموال4',
            text: 'تغطي الدورة التدريبية الأساليب المختلفة لعملية غسل الأموال وكيفية مكافحتها بالطريقة الصحيحة',
            firstText: '٣ أيام',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات الوظيفية',
            thirdIcon: courseIcon6,
        }
    ],
    [
        {
            id: 1,
            title: '5555الادارة الاستراتيجية',
            text: 'تغطى الدورة التدريبية كافة اللوائح الداخلية المالية المعمول بها داخل البنك وكيفية أتباعها بطريقة صحيحة',
            firstText: '٤ أيام',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات الوظيفية',
            thirdIcon: courseIcon3,
        },
        {
            id: 2,
            title: 'المراقبة والمراجعة2',
            text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية الرقابة الداخلية والمراجعة وكيفية متابعتها',
            firstText: 'يومين',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات القيادية',
            thirdIcon: courseIcon4,
        },
        {
            id: 3,
            title: 'إدارة المخاطر3',
            text: 'تهدف الدورة التدريبية إلى تعريفك بأساسيات عملية إدارة المخاطر وكيفية وضع خطة إدارة المخاطر',
            firstText: '٤ أيام',
            firstIcon: courseIcon1,
            secondText: 'مركز تدريب البنك الأهلي',
            secondIcon: courseIcon4,
            thirdText: 'الكفاءات الاساسية',
            thirdIcon: courseIcon5,
        },
        {
            id: 4,
            title: 'غسل الأموال4',
            text: 'تغطي الدورة التدريبية الأساليب المختلفة لعملية غسل الأموال وكيفية مكافحتها بالطريقة الصحيحة',
            firstText: '٣ أيام',
            firstIcon: courseIcon1,
            secondText: 'التدريب الإلكتروني',
            secondIcon: courseIcon2,
            thirdText: 'الكفاءات الوظيفية',
            thirdIcon: courseIcon6,
        }
    ]
];
