export const nameLinkMap = {
  "Audit": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Block chain": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sustainability": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Risk Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "برامج الحوكمة والالتزام": "https://erpprodapp.nbe.ahly.bank/",
  "قانون البنوك الجديد": "https://erpprodapp.nbe.ahly.bank:443/OA_HTML/RF.jsp?function_id=22702&resp_id=-1&resp_appl_id=-1&security_group_id=0&lang_code=US&oas=u6DB_hfuiED9VXPRsgp22w..&params=BIugRMQIPPeHckt36-S66CQb8GO2XSLBDiivY2K80b9Opz74Zp-8WibSthQ280tD2l.2fb8swesWQ.WTNl38nw",
  "International Financial Reporting Standards (IFRS) - Preparation Course": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified management accountant - Part 1  (CMA)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Compliance": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Policies": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cyper Security": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Artificial Intelligence": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Robotic Process Automation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Resilience": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Inclusion": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Analysis": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business Smart": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Crime Scene Investigation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "DownWards Communication": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Engagement and Leadership Perception": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Identify and Mentor Talents": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Leading Transition": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Management Puzzle": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Upwards Communication": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Who moved my Cheese": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CRM": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fintech": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Anti fraud": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE Cards": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Trade Finance": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cyber Security": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Credit Overview": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cheque Provisions": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE Digital Services": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Retail Overview & Liabilities": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE Orientation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "HR tool kit": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Welcome day": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Me, myself and I": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business writing & Business Etiqutte": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "You Win The Locker Room First": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Build Your Customer Persona": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Visualizing": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Coaching Hub": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Positivity Through Uncertainty": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Build your cutomer persona (Design thinking)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Pitching Presentation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cybersecurity Foundations": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Getting a commitment": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Responsibility vs. Accountability": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fred Kofman on Accountability": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Become a Super-Collaborator": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Working with Difficult People": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Teamwork Foundations": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Improve Your Teamwork Skills": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Essentials of Team Collaboration": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Mistakes You Should Avoid at Work": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Developing Your Professional Image": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building Trust": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Why Trust Matters with Rachel Botsman": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Identifying your professional values": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Connecting and Collaborating in a Virtual or Hybrid Workplace": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Holding Yourself AccountableResponsibility & Commitment": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fred Kofman on Making Commitments": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Defining and Achieving Professional Goals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Being an Effective Team Member": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Working on a Cross-Functional Team": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Stepping Up: How Taking Responsibility Changes Everything (getAbstract Summary)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Developing Resourcefulness": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Collaboration Principles and Process": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Customer Service: Handling Abusive Customers": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building Rapport with Customers": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Customer Service Foundations": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Develop Your Customer Service Skills": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Customer Service Mastery: Delight Every Customer": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "How to Organize Your Time and Your Life": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Getting Things Done": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Strategic Planning Foundations": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Strategic Planning: Case Studies": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Creating Positive Conversations with Challenging Customers": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Innovative Customer Service Techniques": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Quality Standards in Customer Service": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business Collaboration in the Modern Workplace": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Leading and Working in Teams": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building High-Performance Teams": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Presenting as a Team": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Creating an Adaptable Team": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Managing Resources Across Project Teams": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Assessing and Improving Strategic Plans": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "The 45-Minute Business Plan": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Organizing an Outline": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Working with Upset Customers": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Using Customer Surveys to Improve Service": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "A Design Thinking Approach to Putting the Customer First": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Psychological Safety: Clear Blocks to Innovation, Collaboration, and Risk-Taking": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Using Questions to Foster Critical Thinking and Curiosity": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Mindful Meditations for Work and Life": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Living into Strategic - التفكير الاستراتيجي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Moving Up to Manager - الآن أصبحت مديرا": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Coaching skills - مهارات التوجيه": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Getting things done - Level 1 - تحديد و تنفيذ الأولويات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business Writing- ادارة المعلومات و البيانات بشكل مهني": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Art of Handling - فن إدارة الخلافات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Emotional Agilityالذكاء العاطفي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Change cycle - إدارة التغيير": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Gold of the deserts kingالتخطيط و التنظيم": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Windjammer - كيفية التركيز على النتائج و تحسين كفاءة العمل": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Getting things done - Level 2 - تحديد و تنفيذ الأولويات - المستوى المتفدم": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Black Horse - إدارة الذات و تطوير الفريق": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "التفكير التحليلى - Analytical thinking": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Negotiation skills - مهارات التفاوض": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Stress management - كيفية إدارة الضغوط": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Visualizing – Advanced - العرض المرئي للمعلومات – المستوى المتقدم": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الاكسيل في سلاسل الامداد": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "FINANO ChainFinance For Supplay Chain": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Professional Diploma in Supply Chain": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Supply Chain ProfessionalCSCP -  Preparation Course": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "البرنامج المتكامل المتخصص في التامينات و التعويضات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sustainability Facility Professional (SFP)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "AutoCAD - basic": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "AutoCAD - Advanced or REVIT": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Microsoft Project": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Project Management Professional Preparation Course": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Project Manaegment Diploma (3 modules)الجامعة الامريكية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "دبلومة إدارة الفنادق": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "دبلومة الاستدامة البيئية في المطاعم - إدارة المطاعم الخضراء": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "القيادة الإدارية في مجال الضيافة والخدمات الفندقية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Mini MBA في الادارة الفندقية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Warehousing process": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Production and Inventory Management - CPIM part 1- Preparation Course": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Artificial Intelligence: Ethics & Societal Challenges": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Positive Psychology: Resilience Skills": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "FinTech Foundations and Overview": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Visualization and Dashboards Using Microsoft Power BI": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to Business Analytics": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Agile Requirements Foundations": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to IT Automation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Internal Control": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Policies and Procedures": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "لائحة العاملين و الجزاءات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ORM": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تحليل القوائم المالية  و التحليل اللائتمانى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "IFRS 9": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "اعمال تنفيذ و متابعة الائتمان": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة فرانكفورت للمشروعات الصغيرة و المتوسطة المستوى الأول ( للعاملين بتخصص SME)اوبرنامج الائتمان المصرفي ( Credit Course ) للعملين بتخصص الشركات الكبرى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certificate In Commercial Credit ( CICC )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الجوانب القانونية للائتمان و التمويل": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "The International Framework For Basel 2,3": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "اشكال الشركات و القوانين الخاصة بها": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "IFRS 9 ( Update )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "اعمال تنفيذ و متابعة الائتمان ( Update )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Artificial Intelligence: An Overview": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Innovation Strategy: Developing Your Fintech strategy": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Visualization Best Practices": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building Resilience as a Leader": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Making the Case for Robotic Process Automation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الاستعلامات المصرفية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الاستعلامات المصرفية ( Update )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Interest Rate and liquidity Risk Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to Asset and Liability Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Analysis & Statements": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Treasury Products": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تحليل القوائم المالية  و التحليل الائتمانى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الديون المتعثرة و كيفية معالجتها": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ضوابط التجارة الخارجية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تحليل القوائم المالية  ( متقدم )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تحليل التدفقات التنقدية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "دورة تحول / حماية الأصول": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Distress & Debt Restructuring": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Bank Regulation - Basel": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Modeling & Forcasting": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Project Finance": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Compliance & AML": "https://erpprodapp.nbe.ahly.bank/",
  "Audit & Control": "https://erpprodapp.nbe.ahly.bank/",
  "Regulations & Legal Aspects": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Monetary & Financial Policies": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE's Strategy & Chart": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE's Products & Services": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE's Policies and Procedures": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Corporate Governance": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data-Driven Decision Making": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Customer Centric Organization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Enterprise Agility": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cybersecurity": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Digital Transformation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Agility & Resilience": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Critical Thinking": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Design Thinking": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "P3O®": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "TOGAF": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "P3M3®": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "COBIT": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Prince 2 Practitioner": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Program Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Portfolio Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Agile Project Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Scrum Master Agile": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "MSP": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "PgMP®": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "MOP®": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "M_o_R®": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "PMI-RMP®": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ITIL Foundation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business Analysis": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Project Management Professional - PMP Certificate": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Prince 2 Foundation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "BCM & DR": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Analysis and Valuation of Investment Projects": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Corporate Valuation Certificate": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Private Equity Certificate": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Merger & Aquistion": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Securitization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sukuk": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE Compliance Programs": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Risk & Crisis Management - Almentor": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Auditing II: The Practice of Auditing - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE Programs": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ORM Polices Awareness - التوعية بسياسات مخاطر التشغيل - NBE Programs": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to Artificial Intelligence (AI) - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Blockchain Basics - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fintech awareness": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Overview of Data Visualization - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Learning Data Analytics: 1 Foundations - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building Resilience - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Using Python for Automation - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Agile Requirements Foundations - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Analytics for Business Professionals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building Resilience as a Leader - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Advanced Agile: The Team's Mindset  - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Artificial Intelligence: An Overview - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Blockchain Business Models- Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE programs": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Visualization Best Practices - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Dominant Risk Management Standards and Frameworks - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Audit Requirements and financial statement - Almetor": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "How customer-centred are you, really?": "https://www.coursera.org/videos/marketing-analytics-customers/xQIz7",
  "Artficial Intelligenceمقدمة في الذكاء الصناعي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة OUSHA": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة IOSH": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة NEBOSH": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Privacy Information Management System (ISO 27701 LA)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ISO 27001 Lead Implementer": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ISO 27001 Lead Auditor": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cyber Security Fundementals (ISO/IEC 27032 Foundation)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CEH - Certified Ethical hacking": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Incident handling": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Penetration Testing": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Vulnerability Handling": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Analysis and Visualization using excel & Power BI": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Analysis and Data Science track": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business data analysis using Microsoft excel": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Digital transformation strategist certificate": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Digital transformation in financial services (Specialization)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "impact from digital transformation (Advanced)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "project management : life cycle and project planning": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Technology (Fintech) Innovations Specialization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Mobile Banking Masterclass": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Digital innovation and transformation in banking": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fundamentals of project planning and Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Retail banking products design and development": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Product Ideation, Design, and Management Specialization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Pricing Strategy Optimization Specialization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Digital Competition in Financial Services": "https://www.coursera.org/",
  "New Distribution Channels in a Global Retail Banking Strategy": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Account Management & Sales Force Design": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Mini Diploma in Sales Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "The Art of Sales: Mastering the Selling Process Specialization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "WIN! - Essential selling skills": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Essential Sales Skills": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sales and CRM Overview": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "The sales Coach": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Advanced Sales Strategies": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "The Future of Payment Technologies": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sales Management Certificate Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business data analysis using Microsoft excel : Part 2": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Excel Analytics | Data Analysis with Pivot-Tables & Charts": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Innovating with the Business Model Canvas": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Survey analysis to gain marketing insights": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Branding: The Creative Journey Specialization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certfied retail banker (CRP)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Retail lending": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "product portfolio managemenet": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Customer experience excellency for banks": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Cards & payments professional": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Firm Level Economics: Consumer and Producer Behavior": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business model canvas: a tool for Entrepreneurs  and innovators": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Lean six sigma yellow belt": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Customer Service Fundamentals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building a customer centric culture": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "De-Escalating conversations for customer service": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Serving Customers using Social Media": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Customer service handling angry callers": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "10 best practice techniques for customer service": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "lean six sigma black belt": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Process improvement": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Customer Experience Journey Mapping": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "إدارة الجودة الشاملة": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "lean six sigma green belt": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Stability and capability in quality improvement": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data analytics for lean six sigma": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Foundations of project management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Agile project management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "impact from digital transformation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "project management: the basics for success": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "AI, Business & the Future of Work": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Balanced Scorecard Management System Professional": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Balanced Scorecard and Key Performance Indicators": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "FMVA (Financial Modeling & Valuation Analyst)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Measuring & Evaluating Bank Performance": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "AFM (Advanced Finacnial Modeling)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Strategy and Business Planning Professional": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sustainable Development Diploma": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Brand management - Advanced": "https://www.coursera.org/learn/branding-and-cx",
  "Brand management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Content strategy": "https://www.coursera.org/learn/social-imc",
  "UX design - Beginner": "https://www.coursera.org/learn/ux-design-fundamentals",
  "UX design - Advanced ( Marketing communication )": "https://www.coursera.org/learn/ux-design-fundamentals",
  "Strategic marketing": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Strategic marketing (Intermediate)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Strategic marketing ( Advanced )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Effective Budgeting & Cost Control": "https://www.coursera.org/learn/budgeting-essentials-development",
  "Financial Accounting: Foundations": "https://www.coursera.org/learn/financial-accounting-basics",
  "Financial Accounting fundametals": "https://www.coursera.org/learn/uva-darden-financial-accounting",
  "مبادئ أساسيات التسويق": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business strategy": "https://www.coursera.org/learn/strategy-business",
  "Personal branding": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Marketing & Competitive Strategies Diploma": "https://www.coursera.org/learn/advanced-competitive-strategy",
  "Media Planning & Buying": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "دورة الصحافة الإلكترونية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Media Planning & Buying - Advanced": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Marketing Metrics in Pricing and Profitability Analysis": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CSR Governance": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Strategic Innovation: Building and Sustaining Innovative Organizations": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ACI Dealing Certificate": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Bourse Game": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ACI Dealing Diploma": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Treasury Risk Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Asset & Liability Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Corporate Credit Course برنامج الائتمان المتكامل للشركات الكبرى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Moodys Credit Track - Level 1  برنامج الائتمان المتخصص Moodys للشركات الكبرى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Modeling in Excel": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Mitigating Credit Risk": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Moodys Corporate Track - Managerialبرنامج الائتمان المتخصص Moodys": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Moodys Corporate Track - Advancedبرنامج الائتمان المتخصص Moodys": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "The New Age of Risk Management Strategy for Business - linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cybersecurity at Work - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to Business Analytics - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Build personal resilience - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Enterprise Agile: Changing Your Culture -linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "What is Corruption: Anti-Corruption and ComplianceCoursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Dominant Risk Management Standards and Frameworks- Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cybersecurity Awareness: Building Your Cybersecurity Vocabulary - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Artificial Intelligence: Ethics & Societal ChallengesCoursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Blockchain Business Models - Coursera": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "AI in Fintech Essential Training - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Analytics for Business Professionals - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Resilience as a Path to Happiness at Work- Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Enterprise Agile: Changing Your Culture  - Linkedin": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CFA - Chartered Financial Analyst": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CMA - Certified Management Accountant": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ACCA - Association of Chartered Certified Accountants": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "FPAC - Certified Corporate Financial Planning and Analysis Professional": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "IFRS Diploma - The International Financial Reporting Standards": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Corporate Financial Statement Analysis": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Accounting": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "GAAP (Generally Accepted Accounting Principles)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Modeling and Forecasting Financial Statements": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CFM- Chartered Financial Modeler": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Artificial intelligence an overview": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Blockchain Basics": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Conferences & Events on market updates and new trends": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Daily Habits to live sustainability": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to risk management 1": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to risk management 2": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "إجراءات ونظم العمل": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "خدمات ومنتجات التجزئة المصرفية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "التمويل الرقمي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الذكاء الصناعي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "حماية حقوق العملاء": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهاده المحامي المصرفي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "لائحة العاملين و الجزاءات وإجراءات العمل": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "قانون البنك المركزي المصري": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "مستقبل البنوك الذكيه": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Frankfurt Level 1 الشهادة المتخصصة في الائتمان المستوي الأول": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "SME Practical Workshop ورشة عمل الائتمان": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Moodys Smes Track Level 1 برنامج الائتمان المتخصص Moodys": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Frankfurt Level 1 الشهادة المتخصصة في الائتمان المستوي الأول": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "SME Practical Workshop ورشة عمل الائتمان": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تحليل الصناعات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "SME Sales Techniques أساليب البيع في مجال المشروعات الصغيرة": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Frankfurt Level 2الشهادة المتخصصة في الائتمان المستوي المتقدم": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Moodys Smes Track - Managerialبرنامج الائتمان المتخصص Moodys": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Moodys Smes Track - Advancedبرنامج الائتمان المتخصص Moodys": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Basel III": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sustainbility & ESG Risk Assesment": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "NBE's Product & Services": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Network Cable Installer (CNCI®)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Network Infrastructure Design Professional (CNIDP®)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Analysis and Data Visualization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Disaster Recovery": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ISTQB Foundation International Software Testing Qualifications Board": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "IT Architecture": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Scrum Master - Agile": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Uninterruptible Power Supply (UPS) Systems": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CRISIS MANAGEMENT AND COMMUNICATION": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "BUSINESS CONTINUITY MANAGEMENT FUNDAMENTALS": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Active Directory": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Datacenter monitoring with systemcenter operation manager,admin systemcenter con": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Microsoft Exchange": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Securing windows server 2016 /2019, identify with windows server 2016/2019": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "IBM- Intorduction to containers/docker, kubernetes&openshift": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Implementing Cisco Application centeric Infrastructure": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Administering system center configuration manager-Course code M20703-1": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Kubernetes security specialist": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cisco Application centeric Infrastructure, Opeations and troubleshooting": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fintech Foundation& applications of financial technology": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "IBM containres orchestration with kubernetes": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to Financial Technology": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "AIX Track": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "RedHat Track": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ITIL Practitioner": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "JAVA Track": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "SQL 2019 Introduction": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Korn & Bash Shell Programming": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle Developer track": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Unix Fundementals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Administering a SQL Database infrastructure": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "AIX Basic and ADMIN": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Querying Data with Transact SQL": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Red Hat Linux Troubleshooting": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Administering Avaya Aura System Manager": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Avaya Aura Contact Center Administration": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CCNA": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CCNP": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CIPTV1": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CNS-220": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "DCIHX": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Service Managmnet": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified business resilience IT professional (CBRITP)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified ISO 22301 BCM Foundation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "PECB Certified Provisional Disaster Recovery Manager": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "AIX Basics": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Active Directory Services With Windows Server": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ASP.NET Core Fundaments": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Automated Testing: End to End": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Citrix XenApp and XenDesktop Help Desk Support": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Cordova": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Analysis and Data Modeling": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "HP Quality Control": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "JAVA API": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle Database 12c Performance Management and Tuning": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fundamentals of SQL": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "OBI Fundamental and advanced Level": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "OBIEE": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Python for data science and machine learning": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "R12.2 Install/Patch/Maintain Oracle E-Business Suite": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "HDI Support Center Analyst": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Installing and Configuring Windows 10": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "JavaScript Core Language": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle Database 12c Administration Workshop Ed 2": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Advanced SQL": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "C# Development Fundamentals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Business Analysis Professional (CBAP)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Science": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Developing Applications with Containers": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Developing ASP.NET MVC 4 Web Applications": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Developing SQL Server Databases": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to PL/SQL": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Introduction to to information security": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ISTQB Foundation - International Software Testing Qualifications Board": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "IT Security Fundamentals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Java SE8 or .Net tracks": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Mobile Dev. (Xamrine - Flutter)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle FCUB Development Toolkit, Dev & Extensibility  Part 1 & 2": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle FLEXCUBE Universal Banking Lending (Oracle)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle FLEXCUBE Web Service Units Generation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle SQL beginner & intermediate levels": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle WebLogic Server 12c: Administration I & II": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Penetration Testing: The Big Picture": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Securing ASP.NET and ASP.NET Core Applications": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fundamental of PL/SQL Level 1 / Level 2": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle BI Publisher 11G R1: Fundamentals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Supporting and Troubleshooting Windows 10": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Windows Operating System Fundamentals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Xamarin Mobile Development": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "jquery": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle FLEXCUBE Interfaces": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "SQL Fundmentals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Creating Automated Browser Tests with Selenium in C#": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building Cross-platform Apps with Xamarin Forms": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Information Systems Security Professional| CISSP (ISC)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Developing ASP.Net Core MVC Web Application": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Devops": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "FCUB Admin & Support 12.0.3": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "JAVA / .NET": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Java SE 8 Fundamentals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "OBDX Installation & Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ODI": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle BI 12c: Administration": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle Database 12c: RAC Administration": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle Performance Tuning for developers": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Secure programing ASP.NET": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Power Systems for AIX II: AIX Implementation and Administration": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle FLEXCUBE Universal Banking Islamic (Oracle)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "SQL Server 2 :AlwaysOn Availability Grops and Failover Cluster Instances": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Entry certificate in business analysis ECBA": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Programming in HTML5 with JavaScript & CSS3": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ReactJS": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "knockout JS": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "SQL Server 1 :AlwaysOn Availability Grops and Failover Cluster Instances": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Load Testing with Visual Studio 2013": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Intermediate JS": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Java OOB": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Optimizing SQL Queries in Oracle.": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Oracle Database 12c: ASM Administration": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Require JS": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "JAVA EE": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Ojet": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Lean Six Sigma Level 1 & 2": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Advanced risk based audit": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fundamentals of risk based audit": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Internal Control Sysyems": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Preparing for an audit": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "The effectiveness of internal control system": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "The future of audit": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الاتجاهات الحديثه في المراجعه الداخليه من منظور المخاطر المصرفيه": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الاطار العام لنظم الرقابه الداخليه": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Conferences & Events ( Local & International )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Correspondent banking financial crime": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Financial Regulation in Emerging Markets and the Rise of Fintech Companies": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "FinTech Security and Regulation (RegTech)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Regtech": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Regtech update and new trends": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الاتجاهات الحديثه في الالتزام المصرفي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الاطار العام لمكافحه غسل الأموال": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الالتزام بالمتطلبات الرقابيه": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "العملات الافتراضيه ومخاطر غسل الأموال وتمويل الإرهاب المتعلقه بها": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "حماية حقوق العملاء ( متقدم )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "حمايه حقوق العملاء": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "حمايه حقوق العملاء ( متقدم )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "حوكمة متقدم": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "قانون الامتثال الضريبي الأمريكي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "مبادي حوكمه البنوك": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "مكافحة غسل الأموال / نظم الحظر  ( متقدم )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "البرنامج المتخصص في المجالات الفنيه للعاملين بقطاع التدقيق على المركز الرئيسي": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تحليل البيانات للمدققين الداخليين": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تقييم أنظمة الرقابه الداخليه وفق اطار COSO": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تقييم أنظمة الرقابه الداخليه وفق اطار COSO": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "البرنامج المتخصص في المجالات الفنيه للعاملين بقطاع التدقيق على ائتمان المركز الرئيسي والاستثمارات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تحليل البيانات للمدققين الداخليين ( متقدم )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "مبادي حوكمة البنوك": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Information Security Manager | CISM \"ISACA\"": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Information Security Auditor | CISA \"ISACA\"": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "SQL & Oracle databases - security": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified in Risk and Information Systems Control (CRISC)": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CIA": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Building Sustainable Quality Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certificate for documentry credit specialists ( CDCS )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certificate for specialists in demand guarantess ( CSDG )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified trade finance professional": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certificate for documentry credit specialists ( CDCS )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified trade finance professional ( CTFP )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الجوانب القانونيه للتعامل على الحسابات والحجوز والتركات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "احكام الاهليه والولايه على المال": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "احكام الشيك": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الجوانب القانونيه للتعامل على الحسابات والحجوز والتركات( مستوي متقدم حالات عمليه )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "احكام الاهليه والولايه على المال ( مستوي متقدم حالات عمليه )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "احكام الشيك ( مستوي متقدم حالات عمليه )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "اعمال السويفت لرسائل الأوراق الماليه": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ACI Operations preparation course": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Data Visulaization": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Derivatives": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Retail products": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Asset & Liability management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الجوانب القانونيه للتعامل على الحسابات والحجوز والتركات( مستوي متقدم حالات عمليه )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "From MT to MX": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Swift ISO 20022": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CITB": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Microsoft office": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الاوعيه الادخاريه": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "الجوانب القانونيه للتعامل على الحسابات والحجوز والتركات ( مستوي متقدم - حالات عمليه )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "احكام الاهليه والولايه على المال ( مستوي متقدم - حالات عمليه )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "التحول الرقمي الفرص القائمه والدروس المستفاده": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "How digital banking and fintech is changing banking ( advanced )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Dispute resolution ( Intermediate - Advanced )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "أنظمة وخدمات الدفع الالكترونى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "المدفوعات الالكترونيه للبطاقات والمحافظ الالكترونيه والتسويات المرتبطة بها ( فيزا / ماستر )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "التحول الرقمي الفرص القائمه والدروس المستفاده ( مستوي متقدم )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Autorization Base 1 ( Visa - Master )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Simulator ( Visa - Master )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "مستقبل خدمات الدفع الالكترونى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "FinTech and the Transformation in Financial Services": "https://www.coursera.org/",
  "شهادة PRBProfessinal Retail Banking": "https://training.moodys.com/moodys/nd/fresco/login/sr/NBE/NBE.html",
  "تحليل بيانات الأعمال باستخدام Excel": "https://www.almentor.net/courses/Business-Data-Analysis-Using-Excel",
  "مقدمة في الذكاء الإصطناعي بإستخدام تقنية التعلّم الآلي": "https://www.almentor.net/courses/Introduction-to-AI-with-Machine-Learning-Method",
  "Introduction to Blockchain for Financial Services": "https://www.coursera.org/",
  "Introduction to Sustainability": "https://www.coursera.org/",
  "Sustainable Development - Ideas and Imaginaries": "https://www.coursera.org/",
  "Future of Payment(Enterprise Agility)": "https://www.coursera.org/",
  "Emotional Resilience During the Pandemic course | almentor.net": "https://nbe.almentor.net/",
  "اكتشاف تزييف الشيكات واثبات الشخصية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "إحالة الفرص البيعية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "اكتشاف تزييف وتزوير العملات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "اكتشاف تزييف تحقيق الشخصية والتوكيلات والاختام": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Blockchainوالثورة الصناعية الرابعة": "https://nbe.almentor.net/search?q=blockchain",
  "Hybrid Cloud": "https://www.coursera.org/",
  "Data Integrity and Analytics": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sustinability": "https://www.coursera.org/",
  "احكام الاهلية والولاية على المال": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "التعامل علي الحسابات والتوكيلات والحجوز والتركات": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Sustinablity": "https://www.coursera.org/",
  "مواجهة أساليب الاحتيال في طلبات الإصدار": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "دور مسئولي الالتزام": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "البرنامج المتكامل للعاملين بقسم المحاسبة بالفروع": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "التميز في خدمة العملاء": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة CISI": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة CWPCertified Wealth Practitioner": "https://training.moodys.com/moodys/nd/fresco/login/sr/NBE/NBE.html",
  "خدمة كبار العملاء RRM": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة CBMCertified Branch Manager": "https://training.moodys.com/moodys/nd/fresco/login/sr/NBE/NBE.html",
  "إحمى فرعك": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Block Chain & HR": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "البرنامج المتكامل للموارد البشرية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Digital HR Certificate Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Strategic HR Leadership certification program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CIPD - Level 7": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Performance Management Systems & KPIs": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Balanced Scorecard Management System Professional": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CIPD - Level 5": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Project management: The Basics for Success": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Dealing with Stakeholders": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Finance for HR professionals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified KPI professional": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "HR Generalist Certification program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business psychology": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "HR governance professionl certificate program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Talent Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Presentation Designing Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Talent Management & Succession Planning": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Talent identification tools and selectionCertificate": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Competency Based Interview": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Talent Acquisition Certification Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "HR Governance Professional Certificate Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Diversity & Inclusion": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Employee engagement & Internal communication": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Well being at workplacefundamentals": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Writing skills for internal communication": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Culture change": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business Partnering for internal communicators": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Compensation & Benefits Certification Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Job analysis": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Job Evaluation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Organizational Development certificate": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Competency Based L&D Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "L&D Certification Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "HR Metrics & Reporting certification program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "People analytics certification program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "HR Business Partner Certification Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "labor law, Social insurance law & pension law": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "CompTIA Network+": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business analysis": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business analysis ( Advanced )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Business Testing ( Advanced )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "How digital banking and Fintech is changing banking": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "How digital banking and Fintech is changing banking ( Advanced )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ISTQB Foundation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Prince 2 Project management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Project management best practices": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "برنامج الائتمان المصرفي  للعملين بتخصص الشركات الكبرىCredit Course": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Credit Structuring & Documentation": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Trade Finance  Risk Base": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Syndicated Loans": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Real Estate Analysis ( Foundations )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Trade & Commodity Finance": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ESG Risk Assessment for Lenders & Asset Managers": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Syndicated Loans ( Update )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Capital Markets Activities": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Real Estate Analysis ( Advanced )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "إدارة مخاطر التجزئة المصرفية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Retail Risk 1": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Distressed Market Series - Retail Banking": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Fraud Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Retail Risk 11": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Retail Risk 111": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Retail Credit Risk Management Reporting": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certified Data Prtection Officer (CDPO) \"PECB\".": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ISO 31000 Risk Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "المعايير الدولية لاحتساب قاعدة راس المال": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ORM Best Practices & updates": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certificate of the Bussiness Continuity Inistitution": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "BCM Program": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "أفضل الممارسات الخاصة بتحديد وتقييم و مراقبة المخاطر التشغيلية ( نماذج تقييم مخاطر التشغيل RCSA )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "مخاطر التشغيل مركز رئيسي - المرحلة الثانية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Advanced Concepts in Risk Management": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة فرانكفورت للمشروعات الصغيرة و المتوسطة المستوى الأول": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Certificate in Small Businees Banking ( CSBB )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "ورشة عمل لدراسة حالة ائتمانية من منظور كافة الأطراف ( مخاطر - متابعة  - استعلامات )": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "البرنامج المتخصص لمجموعات عمل شريحة المشروعات المتوسطة": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "برنامج متخصص عن تحليل الصتاعات وفقا لشرائح السوق": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "شهادة فرانكفورت للمشروعات الصغيرة و المتوسطة المستوى الثانى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تحليل القوائم المالية و التحليل الائتمانى": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "تقييم مخاطر المؤسسات المالية": "سيتم الإعلان عن طريقة التسجيل لاحقا",
  "Analyzing Sovereign & Country Risk": "سيتم الإعلان عن طريقة التسجيل لاحقا"
}